from .LossInterface import LossInterface
from .PaletteLoss import PaletteLoss
from .SaturationLoss import SaturationLoss
from .SymmetryLoss import SymmetryLoss
from .SmoothnessLoss import SmoothnessLoss
from .DetailLoss import DetailLoss
from .EdgeLoss import EdgeLoss
from .GaussianLoss import GaussianLoss
from .TargetLoss import TargetLoss
from .CannyLoss import CannyLoss